version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cloudpark
    volumes:
      - ./data:/var/lib/postgresql/data
